package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

/**
 * Customerexpirence generated by hbm2java
 */
public class Customerexpirence implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private Experience experience;

	public Customerexpirence() {
	}

	public Customerexpirence(Customer customer, Experience experience) {
		this.customer = customer;
		this.experience = experience;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Experience getExperience() {
		return this.experience;
	}

	public void setExperience(Experience experience) {
		this.experience = experience;
	}

}
