package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 * Customer generated by hbm2java
 */

public class Customer implements java.io.Serializable {

	private Integer id;
	private String pesel;
	private String firstName;
	private String surName;
	private String numberEvidence;
	private String phone;
	private String province;
	private String district;
	private String city;
	private String numberHome;
	private String street;
	private Set customerexpirences = new HashSet(0);
	private Set fields = new HashSet(0);

	public Customer() {
	}

	/*public Customer(String pesel, String firstName, String surName,
			String numberEvidence, String phone, String province,
			String district, String city, String numberHome, String street) {
		this.pesel = pesel;
		this.firstName = firstName;
		this.surName = surName;
		this.numberEvidence = numberEvidence;
		this.phone = phone;
		this.province = province;
		this.district = district;
		this.city = city;
		this.numberHome = numberHome;
		this.street = street;
	}*/

	public Customer(String pesel, String firstName, String surName,
			String numberEvidence, String phone, String province,
			String district, String city, String numberHome, String street,
			Set customerexpirences, Set fields) {
		this.pesel = pesel;
		this.firstName = firstName;
		this.surName = surName;
		this.numberEvidence = numberEvidence;
		this.phone = phone;
		this.province = province;
		this.district = district;
		this.city = city;
		this.numberHome = numberHome;
		this.street = street;
		this.customerexpirences = customerexpirences;
		this.fields = fields;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurName() {
		return this.surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getNumberEvidence() {
		return this.numberEvidence;
	}

	public void setNumberEvidence(String numberEvidence) {
		this.numberEvidence = numberEvidence;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getNumberHome() {
		return this.numberHome;
	}

	public void setNumberHome(String numberHome) {
		this.numberHome = numberHome;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Set getCustomerexpirences() {
		return this.customerexpirences;
	}

	public void setCustomerexpirences(Set customerexpirences) {
		this.customerexpirences = customerexpirences;
	}

	public Set getFields() {
		return this.fields;
	}

	public void setFields(Set fields) {
		this.fields = fields;
	}

}
