package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Employer generated by hbm2java
 */
public class Employer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String city;
	private String country;
	private String webAdress;
	private Set experiences = new HashSet(0);

	public Employer() {
	}

	public Employer(String name, String city, String country, String webAdress) {
		this.name = name;
		this.city = city;
		this.country = country;
		this.webAdress = webAdress;
	}

	public Employer(String name, String city, String country, String webAdress,
			Set experiences) {
		this.name = name;
		this.city = city;
		this.country = country;
		this.webAdress = webAdress;
		this.experiences = experiences;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getWebAdress() {
		return this.webAdress;
	}

	public void setWebAdress(String webAdress) {
		this.webAdress = webAdress;
	}

	public Set getExperiences() {
		return this.experiences;
	}

	public void setExperiences(Set experiences) {
		this.experiences = experiences;
	}

}
