package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Plot generated by hbm2java
 */
public class Plot implements java.io.Serializable {

	private Integer id;
	private Field field;
	private String name;
	private String number;
	private String wetness;
	private Float colletionsKg;
	private Set plants = new HashSet(0);

	public Plot() {
	}

	public Plot(Field field, String name, String number) {
		this.field = field;
		this.name = name;
		this.number = number;
	}

	public Plot(Field field, String name, String number, String wetness,
			Float colletionsKg, Set plants) {
		this.field = field;
		this.name = name;
		this.number = number;
		this.wetness = wetness;
		this.colletionsKg = colletionsKg;
		this.plants = plants;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Field getField() {
		return this.field;
	}

	public void setField(Field field) {
		this.field = field;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getWetness() {
		return this.wetness;
	}

	public void setWetness(String wetness) {
		this.wetness = wetness;
	}

	public Float getColletionsKg() {
		return this.colletionsKg;
	}

	public void setColletionsKg(Float colletionsKg) {
		this.colletionsKg = colletionsKg;
	}

	public Set getPlants() {
		return this.plants;
	}

	public void setPlants(Set plants) {
		this.plants = plants;
	}

}
