package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

/**
 * Portionofprotectproduct generated by hbm2java
 */
public class Portionofprotectproduct implements java.io.Serializable {

	private Integer id;
	private Plantprotectprroduct plantprotectprroduct;
	private String dose;

	public Portionofprotectproduct() {
	}

	public Portionofprotectproduct(Plantprotectprroduct plantprotectprroduct,
			String dose) {
		this.plantprotectprroduct = plantprotectprroduct;
		this.dose = dose;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Plantprotectprroduct getPlantprotectprroduct() {
		return this.plantprotectprroduct;
	}

	public void setPlantprotectprroduct(
			Plantprotectprroduct plantprotectprroduct) {
		this.plantprotectprroduct = plantprotectprroduct;
	}

	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

}
