package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set plants = new HashSet(0);

	public Stage() {
	}

	public Stage(String name) {
		this.name = name;
	}

	public Stage(String name, Set plants) {
		this.name = name;
		this.plants = plants;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPlants() {
		return this.plants;
	}

	public void setPlants(Set plants) {
		this.plants = plants;
	}

}
