package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Verification generated by hbm2java
 */
public class Verification implements java.io.Serializable {

	private Integer id;
	private Experience experience;
	private Date date;
	private String comments;

	public Verification() {
	}

	public Verification(Experience experience, Date date, String comments) {
		this.experience = experience;
		this.date = date;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Experience getExperience() {
		return this.experience;
	}

	public void setExperience(Experience experience) {
		this.experience = experience;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
