package com.app.agree.domain;

// Generated 2014-08-13 22:26:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Weed generated by hbm2java
 */
public class Weed implements java.io.Serializable {

	private Integer id;
	private String name;
	private int typ;
	private Set weedofplants = new HashSet(0);
	private Set plants = new HashSet(0);
	private Set fieldweeds = new HashSet(0);

	public Weed() {
	}

	public Weed(String name, int typ) {
		this.name = name;
		this.typ = typ;
	}

	public Weed(String name, int typ, Set weedofplants, Set plants,
			Set fieldweeds) {
		this.name = name;
		this.typ = typ;
		this.weedofplants = weedofplants;
		this.plants = plants;
		this.fieldweeds = fieldweeds;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTyp() {
		return this.typ;
	}

	public void setTyp(int typ) {
		this.typ = typ;
	}

	public Set getWeedofplants() {
		return this.weedofplants;
	}

	public void setWeedofplants(Set weedofplants) {
		this.weedofplants = weedofplants;
	}

	public Set getPlants() {
		return this.plants;
	}

	public void setPlants(Set plants) {
		this.plants = plants;
	}

	public Set getFieldweeds() {
		return this.fieldweeds;
	}

	public void setFieldweeds(Set fieldweeds) {
		this.fieldweeds = fieldweeds;
	}

}
